# Generated by Django 3.2.4 on 2021-06-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
